import { Model } from 'core/models';
export class ItemContents extends Model {
  public itemId?: number;
  public itemCode?: string;
  public itemName?: string;
  public productGroupingId?: number;
  public productGroupingName?: string;
  public productGroupingCode?: string;
  public saleEmployeeId?: number;
  public indirectQuantityPlanned: number;
  public indirectQuantity: number;
  public indirectQuantityRatio: number;
  public indirectRevenuePlanned: number;
  public indirectRevenue: number;
  public indirectRevenueRatio: number;
  public indirectAmountPlanned: number;
  public indirectAmount: number;
  public indirectAmountRatio: number;
  public indirectStorePlanned: number;
  public indirectStore: number;
  public indirectStoreRatio: number;
  public directQuantityPlanned?: number;
  public directQuantity?: number;
  public directQuantityRatio?: number;
  public directRevenuePlanned?: number;
  public directRevenue?: number;
  public directRevenueRatio?: number;
  public directAmountPlanned?: number;
  public directAmount?: number;
  public directAmountRatio?: number;
  public directStorePlanned?: number;
  public directStore?: number;
  public directStoreRatio?: number;
}
